ProjetoPW/urls.py
from django.shortcuts import render
from django.urls import path
from . import views

app_name = "ProjetoPW"

urlpatterns = [
    # Formulário
    path('formulario/', views.formulario_page_view, name='formulario'),

    # Mapa
    path('mapa/', views.mapa_page_view, name='mapa'),

    # Informacao
    path('informacao/', views.informcao_page_view, name='informacao'),

    # Index
    path('index/', views.index_page_view, name='index'),  # ERRO na página do mapa não mostra

    # Celler
    path('cellerIntroducao', views.cellerIntroducao_page_view, name='cellerIntroducao'),
    path('cellerCozinha', views.cellerCozinha_page_view, name='cellerCozinha'),
    path('cellerPinteresse', views.cellerPinteresse_page_view, name='cellerPinteresse'),

    # Mirazur
    path('mirazurIntrodução', views.mirazurIntroducao_page_view, name='mirazurIntroducao'),
    path('mirazurCozinha', views.mirazurCozinha_page_view, name='mirazurCozinha'),
    path('mirazurPinteresse', views.mirazurPinteresse_page_view, name='mirazurPinteresse'),

    # Noma
    path('nomaIntroducao', views.nomaIntroducao_page_view, name='nomaIntroducao'),
    path('nomaCozinha', views.nomaCozinha_page_view, name='nomaCozinha'),
    path('nomaPinteresse', views.nomaPinteresse_page_view, name='nomaPinteresse'),

    # Contacto
    path('', views.contacto_page_view, name='contacto'),
    path('listar/', views.novo_contacto_view, name='listar'),
    path('edita/<int:usuario_id>', views.edita_contacto_view, name="edita"),
    path('apaga/<int:usuario_id>', views.apaga_contacto_view, name="apaga"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('ProjetoPW.urls')),
    path('quizz/', include('quizz.urls')),
]

quizz/urls.py
from django.shortcuts import render
from django.urls import path
from . import views

app_name = "quizz"

urlpatterns = [
    path('quizz/', views.quizz_view, name=""),
    path('submit/', views.SubmitTentativa_view, name="enviar"),
    path('pontuacao/', views.pontuacao_view, name="pontuacao"),
]

ProjetoPW/models.py
from django.db import models

# Create your models here.
class Usuario(models.Model):
    nome = models.CharField(max_length=30, null=False)
    apelido = models.CharField(max_length=30, null=False)
    telefone = models.CharField(max_length=9, null=False)
    email = models.EmailField(null=False)
    dataNascimento = models.DateTimeField(null=False)

    def __str__(self):
        return f"{self.nome} {self.apelido} {self.telefone} {self.email} {self.dataNascimento}"

quizz/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Resposta(models.Model):
    textoResposta = models.CharField(max_length=50)
    correta = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.textoResposta

class Pergunta(models.Model):
    textoPergunta = models.CharField(max_length=200)
    respostas = models.ManyToManyField(Resposta)
    pontos = models.PositiveIntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.textoPergunta

class Quizz (models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    tituloPergunta = models.CharField(max_length=50)
    data = models.DateTimeField (auto_now_add=True)
    due = models.DateField()
    tentativas = models.PositiveIntegerField()
    tempo = models.PositiveIntegerField()
    perguntas = models.ManyToManyField(Pergunta)

    def __str__(self):
        return self.tituloPergunta


class Tentativa(models.Model):
    quizz = models.ForeignKey(Quizz, on_delete=models.CASCADE)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    pergunta = models.ForeignKey(Pergunta, on_delete=models.CASCADE)
    resposta = models.ForeignKey(Resposta, on_delete=models.CASCADE)

    def __str__(self):
        return self.usuario.user.username + ' - ' + self.resposta.textoResposta

ProjetoPW/forms.py
from django import forms
from .models import Usuario

class UsuarioFormulario(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = ["nome", "apelido", "telefone", "email", "dataNascimento"]

quizz/forms.py
from django import forms
from django.forms import ModelForm
from quizz.models import Quizz, Pergunta
from django.db import models

class NovoQuizzFormulario (ModelForm):
    class Meta:
        model = Quizz
        fields = '__all__'

class NovaPerguntaFormulario:
    class Meta:
        model = Quizz
        fields = '__all__'

ProjetoPW/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .models import Usuario
from .forms import UsuarioFormulario
#from .forms QuizzFormulario, PerguntaFormulario

from django.views.generic import ListView

# Create your views here.

# Mapa
def mapa_page_view(request):
    return render(request, 'ProjetoPW/mapa.html')


# Informacao
def informcao_page_view(request):
    return render(request, 'ProjetoPW/informacao.html')


# Formulário
def formulario_page_view(request):
    return render(request, 'ProjetoPW/formulario.html')


# Index
def index_page_view(request):
    return render(request, 'ProjetoPW/index.html')


# Mirazur
def mirazurIntroducao_page_view(request):
    return render(request, 'ProjetoPW/mirazurIntroducao.html')


def mirazurCozinha_page_view(requeste):
    return render(requeste, 'ProjetoPW/mirazurCozinha.html')


def mirazurPinteresse_page_view(requeste):
    return render(requeste, 'ProjetoPW/mirazurPinteresse.html')


# Celler
def cellerIntroducao_page_view(request):
    return render(request, 'ProjetoPW/cellerIntroducao.html')


def cellerCozinha_page_view(requeste):
    return render(requeste, 'ProjetoPW/cellerCozinha.html')


def cellerPinteresse_page_view(requeste):
    return render(requeste, 'ProjetoPW/cellerPinteresse.html')


# Noma
def nomaIntroducao_page_view(request):
    return render(request, 'ProjetoPW/nomaIntroducao.html')


def nomaCozinha_page_view(requeste):
    return render(requeste, 'ProjetoPW/nomaCozinha.html')


def nomaPinteresse_page_view(request):
    return render(request, 'ProjetoPW/nomaPinteresse.html')


# Contacto
def contacto_page_view(request):
    context = {'ProjetoPW': Usuario.objects.all()}
    return render(request, 'ProjetoPW/contacto.html', context)


def novo_contacto_view(request):
    form = UsuarioFormulario(request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('ProjetoPW:contacto'))

    context = {'form': form}

    return render(request, 'ProjetoPW/listar.html', context)


def edita_contacto_view(request, usuario_id):
    usuario = Usuario.objects.get(id=usuario_id)
    form = UsuarioFormulario(request.POST or None, instance=usuario)

    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('ProjetoPW:contacto'))

    context = {'form': form, 'usuario_id': usuario_id}
    return render(request, 'ProjetoPW/edita.html', context)


def apaga_contacto_view(request, usuario_id):
    Usuario.objects.get(id=usuario_id.delete())
    return HttpResponseRedirect(reverse('ProjetoPW:contacto'))

quizz/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from quizz.forms import NovoQuizzFormulario, NovaPerguntaFormulario
from quizz.models import Resposta, Pergunta, Quizz, Tentativa
# Create your views here.

def quizz_view(request):
    context = {'quizzes': Quizz.objects.all(), 'perguntas': Pergunta.objects.all()}
    return render(request, 'quizz.html', context)

    form = NovoQuizzFormulario (request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse(''))
    context = {'form': form}

    return render(request, 'quizz.html', context)

def SubmitTentativa_view (request):
    user = request.user
    pontosGanhos = 0
    quizz_id = request.POST.get('quizz_id')
    quizz = Quizz.objects.get(id=quizz_id)

    r1 = int(request.POST.get('1'))
    r2 = int(request.POST.get('2'))
    r3 = int(request.POST.get('3'))
    r4 = int(request.POST.get('4'))

    if request.method == 'POST':
        pontos = r1 + r2 + r3 + r4

    t = Tentativa.objects.create(
        quizz=quizz,
        pessoa=user,
        pontos=pontos
    )

    t.save()
    return redirect('ProjetoPW/index.html')

def pontuacao_view(request):
    user = request.user
    quizzes = Quizz.objects.all()
    tentativas = Tentativa.objects.all()
    contagem = 0

    for tentativa in tentativas:
        if tentativa.usuario == user:
            contagem = contagem+1

    context = { 'quizz': quizzes, 'tentativas': tentativas,'contagem':contagem}
    return render (request, "pontuacao.html", context)

ProjetoPW/templates/ProjetoPW/contacto.html
{% extends 'ProjetoPW/base.html' %}

{% load static %}

{% block head %}
    <style>
        .parallax {
            background-image: url('{% static "ProjetoPW/images/contacto.png"%}');
            min-height: 500px;
            background-attachment: fixed;
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
        }
        h1{
            font-size: 2vw;
            font-family: 'Dela Gothic One', cursive;
            color:rgb(202, 29, 29);
        }
        p{
            text-align: center;
        }
        .nav{
            background-color:rgb(10, 51, 90);
        }
        .footer{
            background-color:rgb(10, 51, 90);
        }
        fieldset{
            text-align: center;
        }
    </style>
{% endblock head %}

{% block body %}
    <div class="parallax"></div>
{% endblock body %}

{% block header %}
    <h1>Ficha de Contacto</h1>
{% endblock header %}

{% block nav %}
    <a href="{% url 'ProjetoPW:informacao' %}" target="_blank">&#10067; Informações </a>
    <a href="{% url 'ProjetoPW:formulario' %}" target="_blank">&#128203; Formulário </a>
    <a href="{% url 'ProjetoPW:mapa' %}" target="_blank">🗺️ Mapa do Website</a>
    <b><a href="{% url 'ProjetoPW:contacto' %}">📞 Contacto </a></b>
    <a href="{% url 'ProjetoPW:quizz' %}">✍️ Quizz </a>
    <a href="{% url 'ProjetoPW:index' %}" target="_blank">&#128281; Home </a>
{% endblock nav %}


{% block main %}
     {% for usuario in usuarios %}
        <p>
            <a href="{% url 'ProjetoPW:edita' usuario.id %}" class="btn btn-warning  btn-sm" style="float: right; margin-right: 10px">
                Editar
            </a>
        </p>
   {% endfor %}
    <a href="{% url 'ProjetoPW:listar' %}" class="btn btn-success btn-block"> Novo Contacto</a>
{% endblock main %}

{% block body2 %}
    <div class="parallax"></div>
{% endblock body2 %}

ProjetoPW/templates/ProjetoPW/edita.html
{% extends 'ProjetoPW/base.html' %}

{% block main %}
    <h3>Contacto</h3>

    <form action="{% url 'ProjetoPW:edita' usuario_id %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        <a href="{% url 'ProjetoPW:contacto' %}" role="button" class="btn btn-warning">Cancelar</a>
        <input type="submit" value="Gravar" class="btn btn-success" >
        <a href="{% url 'ProjetoPW:apagar' usuario_id %}" role="button" class="btn btn-danger">Apagar</a>
    </form>
{% endblock main %}

ProjetoPW/templates/ProjetoPW/formulario.html
{% extends "ProjetoPW/base.html" %}

{% load static %}

{% block head %}
    <style>
        .parallax {
            background-image: url('{% static "ProjetoPW/images/formulario.png"%}');
            min-height: 500px;
            background-attachment: fixed;
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
        }
        h1{
            font-size: 2vw;
            font-family: 'Dela Gothic One', cursive;
            color:rgb(202, 29, 29);
        }
        p{
            text-align: center;
        }
        .nav{
            background-color:rgb(10, 51, 90);
        }
        .footer{
            background-color:rgb(10, 51, 90);
        }
        fieldset{
            text-align: center;
        }
    </style>
{% endblock head %}

{% block body %}
    <div class="parallax"></div>
{% endblock body %}

     <!--Nav-->
{% block nav %}
        <a href="{% url 'ProjetoPW:informacao' %}" target="_blank">&#10067; Informações </a>
        <b><a href="{% url 'ProjetoPW:formulario' %}" target="_blank">&#128203; Formulário </a></b>
        <a href="{% url 'ProjetoPW:mapa' %}" target="_blank">🗺️ Mapa do Website</a>
        <a href="{% url 'ProjetoPW:contacto' %}">📞 Contacto </a>
        <a href="{% url 'ProjetoPW:quizz' %}">✍️ Quizz </a>
        <a href="{% url 'ProjetoPW:index' %}" target="_blank">&#128281; Home </a>
{% endblock nav %}

    <!--Header-->
{% block header %}
    <h1><b>Formulário</b></h1>
{% endblock header %}

        <!--Conteúdo Principal // Main-->
{% block main %}
    <form autocomplete="off" method="POST" action="nome.apelido@gmail.com">

    <p><b>Ajude-nos a perceber o que melhorar!! &#9997;</b></p>


    <fieldset>
        <legend>Dados Pessoais</legend>
        <span><div class="First_test"><label for="fname">Nome:</label></div></span>
        <input type="text" id="fname" name="fname" placeholder="XXXXXXXX" size="50">
        <span><div class="Second_test"><label for="lname">Apelido:</label></div></span>
        <input type="text" id="lname" name="lname" placeholder="XXXXXXX" size="50">
        <span><div class="Three_test"><label for="email">Email:</label></div></span>
        <input for="email" id="email" name="email" placeholder="nomeutilizador@gmail.com" size="50">
        <span><div class="Four_test"><label type="phone">Número de telemóvel:</label></div></span>
        <input type="tel" id="phone" placeholder="121 345 678" pattern="[0-9]{3}-[0-9]{3}-[0-9]{3}">
    </fieldset>
    <br><br>

    <fieldset>
        <legend>Questões</legend>
        <span><label for="clareza">Como classifica o nosso website quanto à clareza?</label></span>
        <input type="range" id="clareza" name="clareza" min="0" max="100">
        <br><br>

        <span><label for="rigor">Como classifica o nosso website quanto ao rigor?</label></span>
        <input type="range" id="rigor" name="rigor" min="0" max="100">
        <br><br>

        <span><label for="profundidade">Como classifica o nosso website quanto à profundidade?</label></span><br><br>
        <input type="checkbox" id="Avaliar" name="Avaliar" value="Pessimo">
        <label for="Pessimo">Péssimo</label>
        <input type="checkbox" id="Avaliar" name="Avaliar" value="Medio">
        <label for="Medio">Médio</label>
        <input type="checkbox" id="Avaliar" name="Avaliar" value="Bom">
        <label for="Bom">Bom</label>
        <input type="checkbox" id="Avaliar" name="Avaliar" value="Muito Bom">
        <label for="Muito Bom">Muito Bom</label>
        <br><br>

        <span><label for="amplitude">Como classifica o nosso website quanto ao seu layout?</label></span>
        <input type="range" id="amplitude" name="amplitude" min="0" max="100">
        <br><br>

        <span><label for="logica">Como classifica o nosso website quanto à lógica?</label></span>
        <input type="range" id="logica" name="logica" min="0" max="100">
        <br><br>

        <span><label for="significancia">Como classifica o nosso website quanto à estrutura?</label></span>
        <input type="range" id="significancia" name="significancia" min="0" max="100">
        <br><br>

        <span><label for="originalidade">Como classifica o nosso website quanto à originalidade?</label></span><br><br>
        <input type="radio" id="Pessimo" name="gender" value="Pessimo">
        <label for="Pessimo">Péssimo</label>
        <input type="radio" id="Medio" name="gender" value="Medio">
        <label for="Medio">Médio</label>
        <input type="radio" id="Bom" name="gender" value="Bom">
        <label for="Bom">Bom</label>
        <input type="radio" id="Muito Bom" name="gender" value="Muito Bom">
        <label for="Muito Bom">Muito Bom</label>
        <br><br>

        <span><label for="significancia">Como classifica o nosso website quanto às cores?</label></span>
        <input type="range" id="significancia" name="significancia" min="0" max="100">
        <br><br>

        <span><label for="significancia">Como classifica o nosso website quanto às animações?</label></span>
        <input type="range" id="significancia" name="significancia" min="0" max="100">
        <br><br>

        <span><p>Sugestões de Melhoria:</p></span>
        <textarea name="message" rows="3" cols="50">Escreve aqui...</textarea>
        <br><br>
        <input type="hidden" id="lab3" name="lab3" value="100">

        <button type="button" onclick="alert('Submetido')">Submeter</button>

    </fieldset>
    </form>
{% endblock main %}

{% block body2 %}
    <div class="parallax"></div>
{% endblock body2 %}

   <!--Footer-->
{% block footer %}
    <p> Universade Lusófona de Humanidades e Tecnologias </p>
{% endblock footer %}

ProjetoPW/templates/ProjetoPW/index.html
{% extends 'ProjetoPW/base.html' %}

{% load static %}

{% block head %}
    <style>
        .parallax {
            background-image: url('{% static "ProjetoPW/images/capa.jpeg" %}');
            min-height: 500px;
            background-attachment: fixed;
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
        }
        h1{
            font-size: 4vw;
            font-family: 'Dela Gothic One', cursive;
        }
        h2{
            font-size:1.5vw;
            font-family: 'New Tegomin', serif;
        }
        .footer{
            background-color:rgb(31, 95, 138) ;
        }
        /*Menu Dropdown Responsivo*/
        nav ul {
            display: inline;
        }
        nav ul a{
            display: inline-block;
            padding: 3px 1px 3px 2px;
            text-decoration: none;
            color: #FFF;
        }
        nav li{
            display: inline-block;
            position: relative;
        }
        nav a {
            display: inline-block;
            padding: 5px 30px;
            width: 200px;
            height: 100%;
            text-decoration: none;
            color: white;
            background-color: rgb(31, 95, 138);
        }
        nav ul a :hover{
            color: #000;
            background-color:#69C;
        }
        nav > ul > li ul {display: none;}
        nav > ul li:hover > ul {
            display:block;
            position: absolute;
            top: 100%;
            left: 0%;
        }
    </style>
{% endblock head %}

{% block body %}
    <div class="parallax"></div>
{% endblock body %}

{% block nav %}
    <nav style="text-align: center;">
        <ul>
            <li><a href="#"> &#10024; Mirazur</a>
                <ul>
                    <li><a  href="{% url 'ProjetoPW:mirazurIntroducao' %}" > Apresentação </a></li>
                    <li><a href="{% url 'ProjetoPW:mirazurPinteresse' %}"> Pontos de Interesse </a></li>
                    <li><a href="{% url 'ProjetoPW:mirazurCozinha' %}"> Cozinha </a></li>
                </ul>
            </li>
            <li><a href="#" style="width: 300px;"> &#10024; El Celler De Can Roca</a>
                <ul>
                    <li><a  href="{% url 'ProjetoPW:cellerIntroducao' %}" > Apresentação </a></li>
                    <li><a href="{% url 'ProjetoPW:cellerPinteresse' %}"> Pontos de Interesse </a></li>
                    <li><a href="{% url 'ProjetoPW:cellerCozinha' %}"> Cozinha </a></li>
                </ul>
            </li>
            <li><a href="#"> &#10024; Noma</a>
                <ul>
                    <li><a  href="{% url 'ProjetoPW:nomaIntroducao' %}" > Apresentação </a></li>
                    <li><a href="{% url 'ProjetoPW:nomaPinteresse' %}"> Pontos de Interesse </a></li>
                    <li><a href="{% url 'ProjetoPW:nomaCozinha' %}"> Cozinha </a></li>
                </ul>
            </li>
            <li><a href="#" style="width: 300px;">&#10133; Detalhes do Projeto</a>
                <ul>
                      <li><a href="{% url 'ProjetoPW:informacao' %}">Informações</a></li>
                      <li><a href="{% url 'ProjetoPW:mapa' %}"> Mapa do Website </a></li>
                </ul>
            </li>
            <li><a href="{% url 'ProjetoPW:formulario' %}">&#128203; Formulário</a></li>
            <li><a href="{% url 'ProjetoPW:contacto' %}"> Contacto </a></li>
            <li><a href="{% url 'ProjetoPW:quizz' %}"> Quizz </a></li>

        </ul>
    </nav>
{% endblock nav %}

{% block header %}
    <div class="item1">
        <br><br><br><br>
    </div>
{% endblock header %}

{% block article %}
     <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br><br><br><br><br>
{% endblock article %}

{% block body2 %}
    <div class="parallax"></div>
{% endblock body2 %}

ProjetoPW/templates/ProjetoPW/listar.html
{% extends "ProjetoPw/base.html" %}

{% block main %}

    <h3>Novo Contacto</h3>

    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        <a href="{% url 'ProjetoPW:contacto' %}" role="button" class="btn btn-warning">Cancelar</a>
        <input type="submit" value="Gravar" class="btn btn-success" >
    </form>

{% endblock main %}

ProjetoPW/templates/ProjetoPW/mapa.html
{% extends "ProjetoPW/base.html" %}

{% load static %}

{% block head %}
    <style>
        .parallax {
            background-image: url('{% static "ProjetoPW/images/fundo.jpg" %}');
            min-height: 500px;
            background-attachment: fixed;
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
        }
        h1{
            font-size: 2vw;
            font-family: 'Dela Gothic One', cursive;
            color:rgb(10, 51, 90);
        }
        h2{
            font-size:1.5vw;
            font-family: 'New Tegomin', serif;
            background-color: rgb(179, 206, 245);
            color: rgb(58, 57, 57);
        }
        h3{
            color:rgb(29, 46, 77);
            text-align: center;
        }
        .nav{
            background-color:rgb(10, 51, 90);
        }
        .footer{
            background-color:rgb(10, 51, 90);
        }
        /*Menu Dropdown*/
        html, body {
            font-family: Arial, Helvetica, sans-serif;
            margin: 0;
            padding: 0;
        }
        nav ul{
            margin-left: 0;
            padding-left: 0;
            list-style-type: none;
            display: inline-block;
            width: 100%;
        }
    </style>
{% endblock head %}

{% block body %}
    <div class="parallax"></div>
{% endblock body %}

     <!--Nav-->
{% block nav %}
    <a href="{% url 'ProjetoPW:informacao' %}" target="_blank">&#10067; Informações </a>
    <a href="{% url 'ProjetoPW:formulario' %}" target="_blank">&#128203; Formulário </a>
    <b><a href="{% url 'ProjetoPW:mapa' %}" target="_blank">🗺️ Mapa do Website</a></b>
    <a href="{% url 'ProjetoPW:contacto' %}">📞 Contacto </a>
    <a href="{% url 'ProjetoPW:quizz' %}">✍️ Quizz </a>
    <a href="{% url 'ProjetoPW:index' %}" target="_blank">&#128281; Home </a>
{% endblock nav %}


    <!--Header-->
{% block header %}
    <h1>Mapa do Website</h1>
{% endblock header %}

        <!--Main-->
{% block main %}
    <main style="min-width: 50vw">
        <ul>
            <li><a href="#"> Mirazur</a>
                <ul>
                    <li><a  href="{% url 'ProjetoPW:mirazurIntroducao' %}" > Apresentação </a></li>
                    <li><a href="{% url 'ProjetoPW:mirazurPinteresse' %}"> Pontos de Interesse </a></li>
                    <li><a href="{% url 'ProjetoPW:mirazurCozinha' %}"> Cozinha </a></li>
                    <li><a href="{% url 'ProjetoPW:index' %}"></a> Home </li>
                </ul>
            </li>
            <li><a href="#"> El Celler De Can Roca</a>
                <ul>
                    <li><a  href="{% url 'ProjetoPW:cellerIntroducao' %}" > Apresentação </a></li>
                    <li><a href="{% url 'ProjetoPW:cellerPinteresse' %}"> Pontos de Interesse </a></li>
                    <li><a href="{% url 'ProjetoPW:cellerCozinha' %}"> Cozinha </a></li>
                    <li><a href="{% url 'ProjetoPW:index' %}"></a> Home </li>
                </ul>
            </li>
            <li><a href="#"> Noma</a>
                <ul>
                   <li><a  href="{% url 'ProjetoPW:nomaIntroducao' %}" > Apresentação </a></li>
                    <li><a href="{% url 'ProjetoPW:nomaPinteresse' %}"> Pontos de Interesse </a></li>
                    <li><a href="{% url 'ProjetoPW:nomaCozinha' %}"> Cozinha </a></li>
                    <li><a href="{% url 'ProjetoPW:index' %}"></a> Home </li>
                </ul>
            </li>
            <li><a href="#"> Detalhes do Projeto</a>
                <ul>
                    <li><a href="{% url 'ProjetoPW:informacao' %}">Informações</a></li>
                    <li><a href="{% url 'ProjetoPW:mapa' %}"> Mapa do Website </a></li>
                </ul>
            </li>
            <li><a href="{% url 'ProjetoPW:formulario' %}">&#128203; Formulário</a></li>
            <li><a href="{% url 'ProjetoPW:contacto' %}"> Contacto </a></li>
            <li><a href="{% url 'ProjetoPW:quizz' %}"> Quizz </a></li>
        </ul>
    </main>
{% endblock main %}

{% block body2 %}
    <div class="parallax"></div>
{% endblock body2 %}

ProjetoPW/templates/ProjetoPW/quizz.html
{% extends 'ProjetoPW/base.html' %}

{% load static %}

{% block head %}
    <style>
        .parallax {
            background-image: url('{% static "ProjetoPW/images/quizz.jpg"%}');
            min-height: 500px;
            background-attachment: fixed;
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
        }
        h1{
            font-size: 2vw;
            font-family: 'Dela Gothic One', cursive;
            color:rgb(202, 29, 29);
        }
        p{
            text-align: center;
        }
        .nav{
            background-color:rgb(10, 51, 90);
        }
        .footer{
            background-color:rgb(10, 51, 90);
        }
        fieldset{
            text-align: center;
        }
    </style>
{% endblock head %}

{% block body %}
    <div class="parallax"></div>
{% endblock body %}

{% block header %}
    <h1>Quizz</h1>
{% endblock header %}

{% block nav %}
    <a href="{% url 'ProjetoPW:informacao' %}" target="_blank">&#10067; Informações </a>
    <a href="{% url 'ProjetoPW:formulario' %}" target="_blank">&#128203; Formulário </a>
    <a href="{% url 'ProjetoPW:mapa' %}" target="_blank">🗺️ Mapa do Website</a>
    <a href="{% url 'ProjetoPW:contacto' %}">📞 Contacto </a>
    <b><a href="{% url 'ProjetoPW:quizz' %}">✍️ Quizz </a></b>
    <a href="{% url 'ProjetoPW:index' %}" target="_blank">&#128281; Home </a>
{% endblock nav %}


{% block main %}
    {% for quizz in quizzes %}

   {% endfor %}
{% endblock main %}

{% block body2 %}
    <div class="parallax"></div>
{% endblock body2 %}