config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('ProjetoPW.urls')),
    path('quizz/', include('quizz.urls')),
]

quizz/urls.py
from django.shortcuts import render
from django.urls import path
from . import views

app_name = "quizz"

urlpatterns = [
    path('quizz/', views.quizz_view, name=""),
    path('submit/', views.SubmitTentativa_view, name="enviar"),
    path('pontuacao/', views.pontuacao_view, name="pontuacao"),
]

users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path('', views.index_view, name="index"),
    path('login/', views.login_view, name="login"),
    path('logout', views.logout_view, name="logout"),
]

users/models.py
from django.db import models

# Create your models here.

users/views.py
from django.shortcuts import render

# Create your views here.
from django.contrib.auth import logout, login, authenticate
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse


# Create your views here.


def index_view(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('users:login'))
    return render(request, "users/logout.html")


def login_view(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(
                    request,
                    username=username,
                    password=password)

        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('users:index'))
        else:
            return render(request, 'users/login.html', {
                'message': 'Credênciais inválidas.'
            })

    return render(request, 'users/login.html')


def logout_view(request):
    logout(request)
    return render(request, 'users/login.html', {
        'message': 'Logged out'})

users/templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Usuários</title>
</head>
<body>
{% block body %}

{% endblock %}
</body>
</html>

users/templates/users/login.html
{%  extends 'users/base.html' %}

{% block body %}
    <h1>Login</h1>
    {% if message %}
        <div> {{ message }} </div>
    {% endif %}
    <form action="{% url 'users:login' %}" method="POST">
        {% csrf_token %}

        <input type="text" name="username" placeholder="username"><br>
        <input type="password" name="password" placeholder="password"><br>
        <input type="submit" value="Login">
    </form>

{% endblock %}

users/templates/users/logout.html
{% extends 'users/base.html' %}

{% block body %}
    <h1>Welcome, {{ request.user.first_name }}</h1>
    <ul>
        <li>Username: {{ request.user.username }}</li>
        <li>Email: {{ request.user.email }}</li>
    </ul>
    <a href="{% url 'users:logout' %}">Logout</a>
{% endblock %}