ProjetoPW/urls.py
from django.shortcuts import render
from django.urls import path
from . import views

app_name = "ProjetoPW"

urlpatterns = [
    # Formulário
    path('formulario/', views.formulario_page_view, name='formulario'),

    # Mapa
    path('mapa/', views.mapa_page_view, name='mapa'),

    # Informacao
    path('informacao/', views.informcao_page_view, name='informacao'),

    # Index
    path('index/', views.index_page_view, name='index'),  # ERRO na página do mapa não mostra

    # Celler
    path('cellerIntroducao', views.cellerIntroducao_page_view, name='cellerIntroducao'),
    path('cellerCozinha', views.cellerCozinha_page_view, name='cellerCozinha'),
    path('cellerPinteresse', views.cellerPinteresse_page_view, name='cellerPinteresse'),

    # Mirazur
    path('mirazurIntrodução', views.mirazurIntroducao_page_view, name='mirazurIntroducao'),
    path('mirazurCozinha', views.mirazurCozinha_page_view, name='mirazurCozinha'),
    path('mirazurPinteresse', views.mirazurPinteresse_page_view, name='mirazurPinteresse'),

    # Noma
    path('nomaIntroducao', views.nomaIntroducao_page_view, name='nomaIntroducao'),
    path('nomaCozinha', views.nomaCozinha_page_view, name='nomaCozinha'),
    path('nomaPinteresse', views.nomaPinteresse_page_view, name='nomaPinteresse'),

    # Contacto
    path('', views.contacto_page_view, name='contacto'),
    path('listar/', views.novo_contacto_view, name='listar'),
    path('edita/<int:usuario_id>', views.edita_contacto_view, name="edita"),
    path('apaga/<int:usuario_id>', views.apaga_contacto_view, name="apaga"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('ProjetoPW.urls')),
    path('quizz/', include('quizz.urls')),
]

quizz/urls.py
from django.shortcuts import render
from django.urls import path
from . import views

app_name = "quizz"

urlpatterns = [
    path('quizz/', views.quizz_view, name=""),
    path('submit/', views.SubmitTentativa_view, name="enviar"),
    path('pontuacao/', views.pontuacao_view, name="pontuacao"),
]

quizz/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Resposta(models.Model):
    textoResposta = models.CharField(max_length=50)
    correta = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.textoResposta

class Pergunta(models.Model):
    textoPergunta = models.CharField(max_length=200)
    respostas = models.ManyToManyField(Resposta)
    pontos = models.PositiveIntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.textoPergunta

class Quizz (models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    tituloPergunta = models.CharField(max_length=50)
    data = models.DateTimeField (auto_now_add=True)
    due = models.DateField()
    tentativas = models.PositiveIntegerField()
    tempo = models.PositiveIntegerField()
    perguntas = models.ManyToManyField(Pergunta)

    def __str__(self):
        return self.tituloPergunta


class Tentativa(models.Model):
    quizz = models.ForeignKey(Quizz, on_delete=models.CASCADE)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    pergunta = models.ForeignKey(Pergunta, on_delete=models.CASCADE)
    resposta = models.ForeignKey(Resposta, on_delete=models.CASCADE)

    def __str__(self):
        return self.usuario.user.username + ' - ' + self.resposta.textoResposta

quizz/forms.py
from django import forms
from django.forms import ModelForm
from quizz.models import Quizz, Pergunta
from django.db import models

class NovoQuizzFormulario (ModelForm):
    class Meta:
        model = Quizz
        fields = '__all__'

class NovaPerguntaFormulario:
    class Meta:
        model = Quizz
        fields = '__all__'

quizz/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from quizz.forms import NovoQuizzFormulario, NovaPerguntaFormulario
from quizz.models import Resposta, Pergunta, Quizz, Tentativa
# Create your views here.

def quizz_view(request):
    context = {'quizzes': Quizz.objects.all(), 'perguntas': Pergunta.objects.all()}
    return render(request, 'quizz.html', context)

    form = NovoQuizzFormulario (request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse(''))
    context = {'form': form}

    return render(request, 'quizz.html', context)

def SubmitTentativa_view (request):
    user = request.user
    pontosGanhos = 0
    quizz_id = request.POST.get('quizz_id')
    quizz = Quizz.objects.get(id=quizz_id)

    r1 = int(request.POST.get('1'))
    r2 = int(request.POST.get('2'))
    r3 = int(request.POST.get('3'))
    r4 = int(request.POST.get('4'))

    if request.method == 'POST':
        pontos = r1 + r2 + r3 + r4

    t = Tentativa.objects.create(
        quizz=quizz,
        pessoa=user,
        pontos=pontos
    )

    t.save()
    return redirect('ProjetoPW/index.html')

def pontuacao_view(request):
    user = request.user
    quizzes = Quizz.objects.all()
    tentativas = Tentativa.objects.all()
    contagem = 0

    for tentativa in tentativas:
        if tentativa.usuario == user:
            contagem = contagem+1

    context = { 'quizz': quizzes, 'tentativas': tentativas,'contagem':contagem}
    return render (request, "pontuacao.html", context)

quizz/templates/quizz/pontuacao.html
{% extends 'ProjetoPW/base.html' %}

{% load static %}

{% block head %}
    <style>
        .parallax {
            background-image: url('{% static "ProjetoPW/images/quizz.jpg"%}');
            min-height: 500px;
            background-attachment: fixed;
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
        }
        h1{
            font-size: 2vw;
            font-family: 'Dela Gothic One', cursive;
            color:rgb(202, 29, 29);
        }
        p{
            text-align: center;
        }
        .nav{
            background-color:rgb(10, 51, 90);
        }
        .footer{
            background-color:rgb(10, 51, 90);
        }
        fieldset{
            text-align: center;
        }
    </style>
{% endblock head %}

{% block body %}
    <div class="parallax"></div>
{% endblock body %}

{% block header %}
    <h1>Pontuação</h1>
{% endblock header %}

{% block nav %}
    <a href="{% url 'ProjetoPW:informacao' %}" target="_blank">&#10067; Informações </a>
    <a href="{% url 'ProjetoPW:formulario' %}" target="_blank">&#128203; Formulário </a>
    <a href="{% url 'ProjetoPW:mapa' %}" target="_blank">🗺️ Mapa do Website</a>
    <a href="{% url 'ProjetoPW:contacto' %}">📞 Contacto </a>
    <b><a href="{% url 'ProjetoPW:quizz' %}">✍️ Quizz </a></b>
    <a href="{% url 'ProjetoPW:index' %}" target="_blank">&#128281; Home </a>
{% endblock nav %}


{% block main %}
    {% if user.is_authenticated %}
        {% if contagem == 0 %}
            <p> Ainda não existem pontuações.</p>
            <p> Por favor realize o Quizz &#128521;.</p>

            {% for quizz in quizzes %}
                {% for tentativa in tentativas %}
                    {% if tentativa.usuario == request.user %}
                        {% if tentativa.quizz == quizz %}
                            {{ quizz.titulo }}
                            {{ tentativa.pontos }}
                        {% endif %}
                    {% endif %}
                {% endfor %}
            {% endfor %}
        {% endif %}

    {% else %}
        <p>Para aceder às pontuações, necessita de fazer o login e efetuar o Quizz.</p>
    {% endif %}

{% endblock main %}

{% block body2 %}
    <div class="parallax"></div>
{% endblock body2 %}

quizz/templates/quizz/quizz.html
{% extends 'ProjetoPW/base.html' %}

{% load static %}

{% block head %}
    <style>
        .parallax {
            background-image: url('{% static "ProjetoPW/images/quizz.jpg"%}');
            min-height: 500px;
            background-attachment: fixed;
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
        }
        h1{
            font-size: 2vw;
            font-family: 'Dela Gothic One', cursive;
            color:rgb(202, 29, 29);
        }
        p{
            text-align: center;
        }
        .nav{
            background-color:rgb(10, 51, 90);
        }
        .footer{
            background-color:rgb(10, 51, 90);
        }
        fieldset{
            text-align: center;
        }
    </style>
{% endblock head %}

{% block body %}
    <div class="parallax"></div>
{% endblock body %}

{% block header %}
    <h1>Quizz</h1>
{% endblock header %}

{% block nav %}
    <a href="{% url 'ProjetoPW:informacao' %}" target="_blank">&#10067; Informações </a>
    <a href="{% url 'ProjetoPW:formulario' %}" target="_blank">&#128203; Formulário </a>
    <a href="{% url 'ProjetoPW:mapa' %}" target="_blank">🗺️ Mapa do Website</a>
    <a href="{% url 'ProjetoPW:contacto' %}">📞 Contacto </a>
    <b><a href="{% url 'ProjetoPW:quizz' %}">✍️ Quizz </a></b>
    <a href="{% url 'ProjetoPW:index' %}" target="_blank">&#128281; Home </a>
{% endblock nav %}


{% block main %}
    {% if user.is_authenticated %}
        <h2> {{ quizz.0.titulo }}</h2>

        <form action="{% url 'submeter' %}" method="POST">
            {% csrf_token %}
            <input type="hidden" value="{{ quizz.0.id }}" name="quizz_id" id="quizz_id">

            {% for pergunta in perguntas %}
                <div> {{ pergunta.textoPergunta }}</div>

                {% for resposta in pergunta.resposta.all %}
                    <input name="{{pergunta.id}}"
                           {% if resposta.correta %}
                                value="{{ pergunta.pontos }}"
                           {% else %}
                                value = "0"
                           {% endif%}
                                type="radio" style="margin-right: 10%">
                    {{ resposta.textoResposta}}
                {% endfor %}
            {% endfor %}

            <div style="margin-top: 25px">
                <input class="butao" type="submit" value="Submeter"> <a href="{% url 'pontuacao'%}" class="sub-botao">Ver Pontuação</a>
            </div>
        </form>

    {% else %}
        <h2> Para aceder ao quizz, necessita de fazer o login.</h2>
    {% endif %}

{% endblock main %}

{% block body2 %}
    <div class="parallax"></div>
{% endblock body2 %}